### PR TITLE
Update AWS4RequestSigner.cs

### PR DESCRIPTION
**Pull request by branch-slalom**
Use `StringComparer.OrdinalIgnoreCase` when sorting query params

To add some more detail, query params need to be sorted by their "character code point".

> Sort the parameter names by character code point in ascending order. 

https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

The internal AWS4Signer also uses the `OrdinalIgnoreCase`

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L843-L850

### CODE REVIEW

**Comment by tsibelman** [comment]
Please update version number as well.

**Comment by branch-slalom** [comment]
@tsibelman Updated the version number in the csproj. Thanks for the quick response!

**Comment by branch-slalom** [comment]
@tsibelman Have you had a chance to look at the changes? Was hoping to have this merged sooner rather than later

**Comment by tsibelman** [comment]
Hi published the nuget

**Comment by branch-slalom** [comment]
> Hi published the nuget

Thanks!

**Pull request merged**
